apiVersion: apps/v1
kind: Deployment
metadata:
  name: ecommerce-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ecommerce-app
  template:
    metadata:
      labels:
        app: ecommerce-app
    spec:
      containers:
      - name: ecommerce-app
        image: us.icr.io/cloud-divya123/ecommerce-app:latest
        ports:
        - containerPort: 3000
